// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AfterLaunch } from "./AfterLaunch";
import type { PathOverrides } from "./PathOverrides";

export type AppConfig = { paths: PathOverrides, afterLaunch: AfterLaunch, 
/**
 * Show the "these files will change" preview before applying.
 */
confirmFileChanges: boolean, setupComplete: boolean, };
