// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Overlay values as they were written, used to spot in-game changes later.
 */
export type AppliedSettings = { graphics: { [key in string]: string }, applyToGta: boolean, fivemCfg: { [key in string]: string }, };
