// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileOpPlan } from "./FileOpPlan";
import type { PackConflict } from "./PackConflict";
import type { SettingsFilePlan } from "./SettingsFilePlan";

/**
 * Dry-run result shown in the apply preview.
 */
export type ApplyPlan = { profileId: string | null, profileName: string | null, settings: Array<SettingsFilePlan>, files: Array<FileOpPlan>, conflicts: Array<PackConflict>, warnings: Array<string>, 
/**
 * Problems that stop the apply (missing folders, invalid values…).
 */
errors: Array<string>, copyBytes: number, runningProcesses: Array<string>, };
