// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApplyPlan } from "./ApplyPlan";

export type ApplyResult = { plan: ApplyPlan, appliedAt: string, snapshotId: string | null, };
