// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeployedFile } from "./DeployedFile";
import type { PathInfo } from "./PathInfo";
import type { SettingsDrift } from "./SettingsDrift";

export type AppStatus = { paths: Array<PathInfo>, fivemExe: string | null, runningProcesses: Array<string>, activeProfileId: string | null, appliedAt: string | null, settingsDrift: Array<SettingsDrift>, 
/**
 * Pack files that were changed or removed by something else since we installed them.
 */
fileDrift: Array<string>, deployedFiles: Array<DeployedFile>, 
/**
 * Set when an interrupted apply was rolled back at startup.
 */
recoveryNotice: string | null, dataDir: string, };
