// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The raw values currently on disk, plus the subset Loadout would capture
 * into a profile by default.
 */
export type CapturedSettings = { fivemGraphicsFound: boolean, graphicsAll: { [key in string]: string }, graphicsDefault: { [key in string]: string }, fivemCfgFound: boolean, cfgAll: { [key in string]: string }, cfgDefault: { [key in string]: string }, };
