// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether "capture current settings" includes the key by default.
 */
export type CaptureRule = "default" | "optIn";
