// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectOption } from "./SelectOption";

export type Control = { "kind": "select", options: Array<SelectOption>, } | { "kind": "toggle" } | { "kind": "slider", min: number, max: number, step: number, } | { "kind": "number", min: number, max: number, };
