// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppliedSettings } from "./AppliedSettings";
import type { DeployedFile } from "./DeployedFile";

export type DeployState = { activeProfileId: string | null, appliedAt: string | null, applied: AppliedSettings, files: Array<DeployedFile>, };
