// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallRoot } from "./InstallRoot";
import type { OriginalBackup } from "./OriginalBackup";

export type DeployedFile = { root: InstallRoot, 
/**
 * Absolute root folder at the time of deployment.
 */
rootDir: string, 
/**
 * Path relative to `root_dir`, with the casing that's on disk.
 */
path: string, packId: string, 
/**
 * Path of the source file inside the pack.
 */
packPath: string, hash: string, size: number, mtimeMs: number, original: OriginalBackup | null, 
/**
 * Folders we had to create for this file (removed again when empty).
 */
createdDirs: Array<string>, };
