// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileOpKind } from "./FileOpKind";
import type { InstallRoot } from "./InstallRoot";

export type FileOpPlan = { kind: FileOpKind, root: InstallRoot, path: string, packName: string | null, size: number, backsUpOriginal: boolean, restoresOriginal: boolean, note: string | null, };
