// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathKey } from "./PathKey";

/**
 * Folders the UI can ask to open in Explorer.
 */
export type FolderTarget = { "kind": "data" } | { "kind": "logs" } | { "kind": "pack", id: string, } | { "kind": "game", key: PathKey, };
