// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Preset } from "./Preset";
import type { SettingDef } from "./SettingDef";

export type GraphicsSchema = { settings: Array<SettingDef>, presets: Array<Preset>, 
/**
 * Keys that are never captured or applied (hardware identity, replay buffers…).
 */
excluded: Array<string>, };
