// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallRoot } from "./InstallRoot";
import type { PackCategory } from "./PackCategory";
import type { PackLayout } from "./PackLayout";
import type { ProposedFile } from "./ProposedFile";

/**
 * What the import wizard shows before anything is copied. The UI can edit
 * name/category/include and hands the same structure back to import.
 */
export type ImportProposal = { sourcePath: string, sourceName: string, name: string, category: PackCategory, layout: PackLayout, root: InstallRoot, files: Array<ProposedFile>, warnings: Array<string>, };
