// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OriginalBackup = { 
/**
 * File name inside `backups/originals`.
 */
file: string, hash: string, size: number, };
