// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallRoot } from "./InstallRoot";

export type PackConflict = { root: InstallRoot, path: string, packs: Array<string>, winner: string, };
