// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a pack's files go. Detected on import, and the user can override it.
 */
export type PackLayout = "fivemTree" | "modsFolder" | "pluginsFolder" | "gtaAudio";
