// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackFile = { 
/**
 * Destination path relative to the pack's root, `a/b/c.rpf`.
 */
path: string, size: number, hash: string, };
