// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathKey } from "./PathKey";
import type { PathSource } from "./PathSource";

export type PathInfo = { key: PathKey, label: string, path: string | null, exists: boolean, source: PathSource, hint: string, };
