// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PathOverrides = { fivemAppDir: string | null, citizenfxDir: string | null, gtaInstallDir: string | null, gtaDocumentsDir: string | null, };
