// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Profile = { id: string, name: string, 
/**
 * Accent colour, `#rrggbb`.
 */
color: string, notes: string, 
/**
 * Partial overlay for settings.xml: `"graphics/ShadowQuality" -> "1"`.
 */
graphics: { [key in string]: string }, 
/**
 * Also write the graphics overlay to GTA V's own settings.xml (Story/Online).
 */
applyToGta: boolean, 
/**
 * Partial overlay for fivem.cfg: `"profile_fpsFieldOfView" -> "5"`.
 */
fivemCfg: { [key in string]: string }, 
/**
 * Pack ids in priority order (a later pack wins when two packs ship the same file).
 * Files uploaded in the profile (sounds, mods) are packs too, marked with
 * [`Pack::profile_file`].
 */
packs: Array<string>, 
/**
 * Server to join after applying: `ip:port`, a hostname or `cfx.re/join/<code>`.
 */
serverAddress: string | null, serverName: string | null, 
/**
 * The server's logo as a `data:image/…;base64,` URL.
 */
serverIcon: string | null, createdAt: string, updatedAt: string, };
