// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Files a profile carries itself, uploaded when creating or editing it.
 */
export type ProfileFileKind = "weaponSounds" | "residentSounds" | "mod";
