// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressStage } from "./ProgressStage";

export type Progress = { stage: ProgressStage, done: number, total: number, message: string, };
