// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProposedFileKind } from "./ProposedFileKind";

export type ProposedFile = { 
/**
 * Path inside the source folder/archive.
 */
source: string, 
/**
 * Destination relative to the install root (docs: relative to the pack's docs folder).
 */
dest: string, kind: ProposedFileKind, reason: string | null, size: number, include: boolean, };
