// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Server = { id: string, name: string, 
/**
 * `ip:port`, a hostname, or `cfx.re/join/<code>`.
 */
address: string, 
/**
 * Profile applied before connecting. `None` connects without changing anything.
 */
profileId: string | null, lastPlayedAt: string | null, };
