// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A server from the FiveM server list, as shown in search results.
 */
export type ServerListing = { 
/**
 * The cfx.re join code: the server joins as `cfx.re/join/<id>`.
 */
id: string, name: string, description: string | null, players: number, maxPlayers: number, 
/**
 * The logo on cfx.re's CDN, when the server has one.
 */
iconUrl: string | null, tags: Array<string>, locale: string | null, };
