// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a server lookup found: shown before the user saves it into a profile.
 */
export type ServerInfo = { 
/**
 * The normalised address, as stored in a profile.
 */
address: string, name: string | null, 
/**
 * The server's logo as a `data:image/…;base64,` URL.
 */
icon: string | null, players: number | null, maxPlayers: number | null, };
