// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerListing } from "./ServerListing";

export type ServerSearch = { 
/**
 * The best matches, most relevant first.
 */
results: Array<ServerListing>, 
/**
 * How many servers matched (there may be more than `results`).
 */
matches: number, 
/**
 * How many servers are listed right now.
 */
total: number, };
