// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureRule } from "./CaptureRule";
import type { Control } from "./Control";
import type { SettingGroup } from "./SettingGroup";

export type SettingDef = { key: string, label: string, description: string, group: SettingGroup, control: Control, capture: CaptureRule, verified: boolean, };
