// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyChange } from "./KeyChange";
import type { SettingsTarget } from "./SettingsTarget";

export type SettingsFilePlan = { target: SettingsTarget, path: string, changes: Array<KeyChange>, 
/**
 * Keys that couldn't be written (no matching section in the file).
 */
skipped: Array<string>, };
