// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsTarget } from "./SettingsTarget";

export type SnapshotFile = { target: SettingsTarget, 
/**
 * Where the file lives in the game folders.
 */
originalPath: string, 
/**
 * File name inside the snapshot folder.
 */
file: string, };
