// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnapshotFile } from "./SnapshotFile";

export type Snapshot = { id: string, createdAt: string, label: string, files: Array<SnapshotFile>, 
/**
 * Pinned snapshots (the first-run backup) are never pruned.
 */
pinned: boolean, };
